#!/usr/bin/bash

# Twitch VOD+overlay batch renderer
# Usage: ./batchdl file
# where file has a vod id and output file name on each line
# example
# 2702983222 threedogg-resi-dc

# to-do:
# - batch render with timestamps (start+end times)

# input file format:
# -i vod-id -o output-file-name -b start-time -e end-time

# Debug
# set -x

VODFILE=$1
SCRIPT="twitchvods"

echo "Reading from file: $VODFILE"

if [ ! -f "$VODFILE" ]; then
	echo "Error: $VODFILE not found."
	exit 1
fi

while IFS= read -r line; do
	if [ -z "$line" ]; then
		continue
	fi
	echo "$line"
	./$SCRIPT $line < /dev/null
done < "$VODFILE"
